# Generated by Django 2.1 on 2018-12-11 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobbies',
            name='userProf',
        ),
    ]
