# Generated by Django 2.1.2 on 2018-12-11 17:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_remove_hobbies_userprof'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='PicFolder/'),
            preserve_default=False,
        ),
    ]
