# Generated by Django 2.1.2 on 2018-12-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_userprofile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Hobbies',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hobUser',
            field=models.ManyToManyField(to='Website.Hobby'),
        ),
    ]
